---
title: "team_fielding"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(ggplot2)
library(fmsb)
```

```{r}
team_fielding <- read.csv('team_fielding.csv')

df1 <- team_fielding%>%
  select(Tm,RA.G,DefEff,Ch,PO,E)
df1 <- df1[-32, ]

df2 <- df1%>%
  select(-Tm)

df2 <- as.data.frame(scale(df2, center = FALSE))

rownames(df2) <- df1$Tm
df2$Tm = df1$Tm

max_row <- apply(df2, 2, max)
min_row <- apply(df2, 2, min)

max_row$Tm='max_row'
min_row$Tm='min_row'
df2 <- rbind(df2, max_row, min_row)




df3 <- df2%>%
  filter(Tm=='max_row'| Tm=='min_row' |
  Tm=='Washington Nationals' |
    Tm=='League Average'| Tm=='Los Angeles Dodgers')%>%
  select(-Tm)

rownames(df3) <- c('max_row','min_row','Washington Nationals', 'League Average', 'Los Angeles Dodgers')
df3$RA.G=as.numeric(df3$RA.G)
df3$DefEff=as.numeric(df3$DefEff)
df3$Ch=as.numeric(df3$Ch)
df3$PO=as.numeric(df3$PO)
df3$E=as.numeric(df3$E)
```

```{r}


# Color vector
colors_border= c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9),rgb(0.7,0.5,0.1,0.9)  )
colors_in= c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4),rgb(0.7,0.5,0.1,0.4)  )

radarchart(df3  , axistype=1 , 
    #custom polygon
    pcol=colors_border , pfcol=colors_in , plwd=4 , plty=1,
    #custom the grid
    cglcol="grey", cglty=1, axislabcol="grey", cglwd=0.8,
    #custom labels
    vlcex=0.8 
    )

# Add a legend
legend(x=1, y=1, legend = rownames(df3[-c(1,2),]))

```

```{r}
library(plotly)
theta_labels <- colnames(df3)
fig <- plot_ly(
    type = 'scatterpolar',
    fill = 'toself'
  ) 
fig <- fig %>%
  add_trace(
    r = c(0.9791112, 0.9831534, 0.9836582, 0.9837703, 0.9720916),
    theta = colnames(df3),
     text = paste("Washington:",theta_labels, "<br>Value:", c(5.22, 0.682,5880,4285, 90)),
    name = 'Washington Nationals'
  ) 
fig <- fig %>%
  add_trace(
    r = c(1.252499,1.022992,1.023215,0.9956422,1.353985),
    theta = colnames(df3),
    text=paste("Average:",theta_labels,"<br>Value:", c(4.62,0.691,5794,4309,84)),
    name = 'Average'
  ) 
fig <- fig %>%
  layout(
    polar = list(
      radialaxis = list(
        visible = T,
        range = c(0,1.5)
      )
    )
  )

fig

```
